# Compiler
CC = gcc

# Compiler flags
CFLAGS = -Wall -Wextra

# Source files directory
SRC_DIR = src

# Source files
SRCS = $(wildcard $(SRC_DIR)/*.c)

# Output binary
OUT = chess.exe

# Compile all source files
all: $(OUT)

$(OUT): $(SRCS)
	$(CC) $(CFLAGS) $(SRCS) -o $(OUT)
	$(OUT)

# Clean the build
clean:
	del /F /Q $(OUT)
